### ISSUE TITLE
sph.image plotting error... But resolves if you run twice.

### ISSUE THREAD

**Issue by earnric** [pynbody/pynbody#295]
I'm seeing the following error with the latest version (28 Nov) of pynbody ... I have it merged out to my fix for log cbar labels, but the error occurs when passing an axis object to smh.image()
```
coords= [-rx,-ry,-rz] # Translation requires negative of the coord
with pynbody.transformation.translate(impData,coords):
    fig = plt.figure()
    ax = fig.add_subplot(111)
    im = sph.image(impData.g,qty="temp",width=smallbox,cmap="RdYlBu_r", denoise=True ,av_z=False, log=True, subplot=ax, approximate_fast=False,qtytitle="$log_{10}\; Temp\, [K]$" ,show_cbar=True)
    plt.show()
```
Here's the error... Note that rerunning the same sph.image() call clears the error and the plot is saved just fine... 

```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-11-1447ab4ec2ee> in <module>()
      5     im = sph.image(impData.g,qty="temp",width=smallbox,cmap="RdYlBu_r", denoise=True ,av_z=False, #ret_im=True,
      6                    log=True, subplot=ax, approximate_fast=False,qtytitle="$log_{10}\; Temp\, [K]$"
----> 7                    ,show_cbar=True
      8                   ); #vmin=0.006, vmax=1.0,
      9     #cbar = fig.colorbar(im)

/Users/earnric/anaconda/lib/python3.4/site-packages/pynbody/plot/sph.py in image(sim, qty, width, resolution, units, log, vmin, vmax, av_z, filename, z_camera, clear, cmap, title, qtytitle, show_cbar, subplot, noplot, ret_im, fill_nan, fill_val, linthresh, **kwargs)
    408     else:
    409         im = sph.render_image(sim, qty, width / 2, resolution, out_units=units,
--> 410                               kernel=kernel,  z_camera=z_camera, **kwargs)
    411 
    412     if fill_nan:

/Users/earnric/anaconda/lib/python3.4/site-packages/pynbody/sph/__init__.py in render_image(snap, qty, x2, nx, y2, ny, x1, y1, z_plane, out_units, xy_units, kernel, z_camera, smooth, smooth_in_pixels, force_quiet, approximate_fast, threaded, denoise)
    494                                     out_units, xy_units, kernel, z_camera, smooth,
    495                                     smooth_in_pixels, True,
--> 496                                     num_threads=threaded)
    497     else:
    498         im = base_renderer(snap, qty, x2, nx, y2, ny, x1, y1, z_plane,

/Users/earnric/anaconda/lib/python3.4/site-packages/pynbody/sph/__init__.py in _threaded_render_image(fn, s, *args, **kwargs)
    372 
    373     # Each output is a 1-element list with a numpy array. Sum them.
--> 374     return sum([o[0] for o in outputs])
    375 
    376 

/Users/earnric/anaconda/lib/python3.4/site-packages/pynbody/sph/__init__.py in <listcomp>(.0)
    372 
    373     # Each output is a 1-element list with a numpy array. Sum them.
--> 374     return sum([o[0] for o in outputs])
    375 
    376 

IndexError: list index out of range
```

**Comment by apontzen** [comment]
Seems like (at least) one of the threads fails, which then leads to you seeing this error when it tries to sum the output from the different threads. I think python 2 used to also print information about why the thread terminated - does this not happen in python 3?

If this persists perhaps you could post an example using the testdata so that I can reproduce it myself.

**Comment by earnric** [comment]
I am using python 3 on my MacPro... I don't see anything else in the error output, let me play with it for a bit and see if I can tease out more information. 
The RAMSES output files I am using are rather large. Where do you suggest I post them? Just dropbox?

**Comment by apontzen** [comment]
Ideally would be better to reproduce it with the existing Ramses test snapshot in the testdata http://star.ucl.ac.uk/~app/testdata.tar.gz

**Comment by jegarfa** [comment]
Hello. I ran a cosmological box in RAMSES and I have the same problem to visualizate the output. All works with the test data file and pynbody, but with my output file does not work. I have not been able to visualize any of my files. Could you help me?
[output_00011.tar.gz](https://github.com/pynbody/pynbody/files/265314/output_00011.tar.gz)

**Comment by jakobherpich** [comment]
I experience a very similar issue with `python3` that I did not experience with `python2`. I believe that I figured out the source of the error. I get the following error message for every thread before I get a traceback that looks very similar to the one posted above. The error occurs in the `_render_image` function in line 592 of `__init__.py` for the sph module because `nx` and `ny` are floats and not integers.

I don't know if a simple cast to integer type would fix the problem. It might cause additional issues because `nx` and `ny` are being modified in the function.

The error message for an individual thread:
```
Exception in thread Thread-719:
Traceback (most recent call last):
  File "/usr/lib64/python3.4/threading.py", line 911, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.4/threading.py", line 859, in run
    self._target(*self._args, **self._kwargs)
  File "/home/herpich/python/pynbody/sph/__init__.py", line 413, in bridge
    X = fn(*args[1:], **kwargs)
  File "/home/herpich/python/pynbody/sph/__init__.py", line 395, in render_fn
    base = fn(*args, **kwargs)
  File "/home/herpich/python/pynbody/sph/__init__.py", line 592, in _render_image
    result = np.zeros((ny, nx), dtype=np.float32)
TypeError: 'float' object cannot be interpreted as an integer
```

The traceback:
```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-13-25b26aee6fb7> in <module>()
----> 1 pynbody.plot.stars.render(sim)

/home/herpich/python/pynbody/plot/stars.py in render(sim, filename, r_band, g_band, b_band, r_scale, g_scale, b_scale, dynamic_range, mag_range, width, starsize, plot, axes, ret_im, clear, ret_range)
    143 
    144     r = image(sim.s, qty=r_band + '_lum_den', width=width, log=False,
--> 145               units="pc^-2", clear=False, noplot=True) * r_scale
    146     g = image(sim.s, qty=g_band + '_lum_den', width=width, log=False,
    147               units="pc^-2", clear=False, noplot=True) * g_scale

/home/herpich/python/pynbody/plot/sph.py in image(sim, qty, width, resolution, units, log, vmin, vmax, av_z, filename, z_camera, clear, cmap, title, qtytitle, show_cbar, subplot, noplot, ret_im, fill_nan, fill_val, linthresh, **kwargs)
    410     else:
    411         im = sph.render_image(sim, qty, width / 2, resolution, out_units=units,
--> 412                               kernel=kernel,  z_camera=z_camera, **kwargs)
    413 
    414     if fill_nan:

/home/herpich/python/pynbody/sph/__init__.py in render_image(snap, qty, x2, nx, y2, ny, x1, y1, z_plane, out_units, xy_units, kernel, z_camera, smooth, smooth_in_pixels, force_quiet, approximate_fast, threaded, denoise)
    500                                     out_units, xy_units, kernel, z_camera, smooth,
    501                                     smooth_in_pixels, True,
--> 502                                     num_threads=threaded)
    503     else:
    504         im = base_renderer(snap, qty, x2, nx, y2, ny, x1, y1, z_plane,

/home/herpich/python/pynbody/sph/__init__.py in _threaded_render_image(fn, s, *args, **kwargs)
    378 
    379     # Each output is a 1-element list with a numpy array. Sum them.
--> 380     return sum([o[0] for o in outputs])
    381 
    382 

/home/herpich/python/pynbody/sph/__init__.py in <listcomp>(.0)
    378 
    379     # Each output is a 1-element list with a numpy array. Sum them.
--> 380     return sum([o[0] for o in outputs])
    381 
    382 

IndexError: list index out of range
```
