### ISSUE TITLE
different array dtypes for gadget file

### ISSUE THREAD

**Issue by dumasj** [pynbody/pynbody#301]
s = pynbody.load('snapshot_004')
pynbody.plot.sph.image(s.star, qty='mass', width=100, cmap='Blues')

I cannot generate a plot because the position and mass arrays have different dtypes for Gadget2 and P-Gadget3 snapshots. I get the following error.

Exception in thread Thread-8:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/site-packages/pynbody/sph/__init__.py", line 407, in bridge
    X = fn(*args[1:], **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pynbody/sph/__init__.py", line 389, in render_fn
    base = fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pynbody/sph/__init__.py", line 535, in _render_image
    snap_proxy[arname] = snap[arname]
  File "/usr/local/lib/python2.7/site-packages/pynbody/snapshot/__init__.py", line 242, in __getitem__
    return self._get_array_with_lazy_actions(i)
  File "/usr/local/lib/python2.7/site-packages/pynbody/snapshot/__init__.py", line 335, in _get_array_with_lazy_actions
    self.__derive_if_required(name)
  File "/usr/local/lib/python2.7/site-packages/pynbody/snapshot/__init__.py", line 350, in __derive_if_required
    self._derive_array(name)
  File "/usr/local/lib/python2.7/site-packages/pynbody/snapshot/__init__.py", line 1915, in _derive_array
    self.base._derive_array(array_name, self._unifamily)
  File "/usr/local/lib/python2.7/site-packages/pynbody/snapshot/__init__.py", line 1444, in _derive_array
    result = fn(self[fam])
  File "/usr/local/lib/python2.7/site-packages/pynbody/sph/__init__.py", line 114, in smooth
    build_tree_or_trees(self)
  File "/usr/local/lib/python2.7/site-packages/pynbody/sph/__init__.py", line 106, in build_tree_or_trees
    build_tree(sim)
  File "/usr/local/lib/python2.7/site-packages/pynbody/sph/__init__.py", line 87, in build_tree
    leafsize=config['sph']['tree-leafsize'])
  File "/usr/local/lib/python2.7/site-packages/pynbody/sph/kdtree.py", line 30, in __init__
    self.kdtree = kdmain.init(pos, mass, int(leafsize))
ValueError: pos and mass arrays must have matching dtypes for kdtree

Traceback (most recent call last):
  File "profile2_test.py", line 35, in <module>
    pynbody.plot.sph.image(s.star, qty='mass', width=100, cmap='Blues');
  File "/usr/local/lib/python2.7/site-packages/pynbody/plot/sph.py", line 394, in image
    kernel=kernel,  z_camera=z_camera, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pynbody/sph/__init__.py", line 496, in render_image
    num_threads=threaded)
  File "/usr/local/lib/python2.7/site-packages/pynbody/sph/__init__.py", line 374, in _threaded_render_image
    return sum([o[0] for o in outputs])
IndexError: list index out of range

**Comment by apontzen** [comment]
I'd create a copy of the mass array with the dtype you want, e.g.

```python
mass = np.asanyarray(s['mass'], dtype=s['pos'].dtype)
del s['mass']
s['mass']=mass
```

then try again. Btw, you almost certainly don't want `qty='mass'` in your image call; you probably mean `qty='rho'` (Which is anyway the default)

**Comment by dumasj** [comment]
Thanks, I can now generate the plot. I did mean qty='rho' in the image call.
