### ISSUE TITLE
Cannot import pynbody, undefined symbol

### ISSUE THREAD

**Issue by clank001** [pynbody/pynbody#305]
Hi, I have tried installing pynbody using pip and manually however when I try to import pynbody in python I get the following error

>>> import pynbody
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/cosma5/data/dp004/dc-arm1/anaconda/lib/python2.7/site-packages/pynbody/__init__.py", line 21, in <module>
    from . import util, filt, array, family, snapshot
  File "/cosma5/data/dp004/dc-arm1/anaconda/lib/python2.7/site-packages/pynbody/util.py", line 27, in <module>
    from ._util import *
ImportError: /cosma5/data/dp004/dc-arm1/anaconda/lib/python2.7/site-packages/pynbody/_util.so: undefined symbol: __kmpc_reduce_nowait

Any ideas as to why it is not working?

**Comment by apontzen** [comment]
Google, first hit:

https://software.intel.com/en-us/forums/intel-math-kernel-library/topic/280759

Looks like a problem with intel compilers. Try following the advice in this post.
