### ISSUE TITLE
Snapshot writing/reading error

### ISSUE THREAD

**Issue by ibackus** [pynbody/pynbody#325]
Recently I have not been able to save tipsy snapshots and I cannot figure out why.  I've never had this problem before, but whenever I create a new snapshot and write it out I cannot properly read it in.  When I load the snapshot, accessing any values (`'pos'`, `'vel'`, etc.) raises an error.  I've pulled the most recent master branch of pynbody and am using numpy version 1.9.2.  Any help would be much appreciated.  Here's an example:

```python
f = pynbody.new(gas=20)

f.write(fmt=pynbody.tipsy.TipsySnap, filename='glass.std')
INFO:pynbody.snapshot.tipsy:Writing main file glass.std
INFO:pynbody.snapshot.tipsy:Writing auxiliary arrays

f2 = pynbody.load('glass.std')
INFO:pynbody.snapshot.tipsy:Loading glass.std
INFO:pynbody.snapshot:Loading using backend <class 'pynbody.snapshot.tipsy.TipsySnap'>
INFO:pynbody.snapshot.tipsy:Loading glass.std

f2['x']
INFO:pynbody.snapshot.tipsy:Loading data from main file glass.std
Traceback (most recent call last):

  File "<ipython-input-47-32ecce976d8a>", line 1, in <module>
    f2['x']

  File "/usr/local/lib/python2.7/dist-packages/pynbody/snapshot/__init__.py", line 242, in __getitem__
    return self._get_array_with_lazy_actions(i)

  File "/usr/local/lib/python2.7/dist-packages/pynbody/snapshot/__init__.py", line 333, in _get_array_with_lazy_actions
    self.__load_if_required(name)

  File "/usr/local/lib/python2.7/dist-packages/pynbody/snapshot/__init__.py", line 344, in __load_if_required
    self.__load_array_and_perform_postprocessing(name)

  File "/usr/local/lib/python2.7/dist-packages/pynbody/snapshot/__init__.py", line 865, in __load_array_and_perform_postprocessing
    self._load_array(array_name, fam)

  File "/usr/local/lib/python2.7/dist-packages/pynbody/snapshot/tipsy.py", line 739, in _load_array
    self._load_main_file()

  File "/usr/local/lib/python2.7/dist-packages/pynbody/snapshot/tipsy.py", line 212, in _load_main_file
    buf = np.fromstring(f.read(st_len * readlen), dtype=dtype)

ValueError: string size must be a multiple of element size
```

**Comment by ibackus** [comment]
It took me a while, but I think I see how to get around this.  The directory I was working in had some other `.param` files (for other snapshots) which had specified that the position and velocity were doubles (`bDoublePos=1` and `bDoubleVel=1`).  Even when I specified the correct param file to use by doing:
```python
f2 = pynbody.load('glass.std', paramname='glass.param')
```
I still get the same error.  But when I move to different working directory, everything works just fine.  I'm pretty sure this is not the expected behavior.
