### ISSUE TITLE
[ramses] unable to create shared memory region

### ISSUE THREAD

**Issue by biernackip** [pynbody/pynbody#327]
Hi!

I want to analyse bunch of outputs from ramses, so I load them in the loop one by one, centering with the analysis.angmom.faceon() call. It works for the first two loops and then it crashes with the following:
`Traceback (most recent call last):
  File "plot_z_vz_hist_2d.py", line 29, in <module>
    pynbody.analysis.angmom.faceon(ds)
  File "/home/ics/biernack/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/pynbody/analysis/angmom.py", line 157, in faceon
    return sideon(h, calc_faceon_matrix, **kwargs)
  File "/home/ics/biernack/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/pynbody/analysis/angmom.py", line 116, in sideon
    cen = halo.center(h, retcen=True, **kwargs)
  File "/home/ics/biernack/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/pynbody/analysis/halo.py", line 304, in center
    return fn(sim, **kwargs)
  File "/home/ics/biernack/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/pynbody/analysis/halo.py", line 83, in shrink_sphere_center
    r = (sim["x"].max() - sim["x"].min()) / 2
  File "/home/ics/biernack/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/pynbody/snapshot/__init__.py", line 263, in __getitem__
    return self._get_array_with_lazy_actions(i)
  File "/home/ics/biernack/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/pynbody/snapshot/__init__.py", line 354, in _get_array_with_lazy_actions
    self.__load_if_required(name)
  File "/home/ics/biernack/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/pynbody/snapshot/__init__.py", line 365, in __load_if_required
    self.__load_array_and_perform_postprocessing(name)
  File "/home/ics/biernack/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/pynbody/snapshot/__init__.py", line 886, in __load_array_and_perform_postprocessing
    self._load_array(array_name, fam)
  File "/home/ics/biernack/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/pynbody/snapshot/ramses.py", line 753, in _load_array
    self._load_gas_vars()
  File "/home/ics/biernack/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/pynbody/snapshot/ramses.py", line 589, in _load_gas_vars
    self.gas._create_array(i)
  File "/home/ics/biernack/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/pynbody/snapshot/__init__.py", line 1914, in _create_array
    array_name, self._unifamily, ndim, dtype, derived, shared)
  File "/home/ics/biernack/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/pynbody/snapshot/__init__.py", line 1177, in _create_family_array
    new_ar = array._array_factory(dims, dtype, False, shared)
  File "/home/ics/biernack/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/pynbody/array.py", line 1019, in _array_factory
    raise MemoryError, "Unable to create shared memory region"
MemoryError: Unable to create shared memory region`
I could use it previously like that, so I have no idea what's going on.

**Comment by apontzen** [comment]
There are two separate issues here.

First, your system is limiting the amount of shared memory available. If you want to raise that limit, see e.g. https://www.zabbix.org/wiki/How_to/configure_shared_memory

Second, there must be uncollected references to your previous files which is why the memory usage is increasing. You can try using `import gc; gc.collect()` to force python to collect the garbage at the start of each cycle. But if that doesn't work, you'll need to figure out what is hanging on to the reference.

**Comment by biernackip** [comment]
Thanks for looking into it, Andrew!
I think the setup for the shared memory didn't change, but I am going to confirm it with our system administrator.

Garbage collection solved the issue - thanks!
