### ISSUE TITLE
Slow tipsy write for auxiliary array

### ISSUE THREAD

**Issue by ibackus** [pynbody/pynbody#371]
I have a snapshot with 10^8 particles which I want to save with the tipsy format which has 1 auxiliary array to write.  Writing the main snapshot file is rapid, it writes the 4.5 GB file in 20s, a healthy write speed of 220MB/s, but writing the auxiliary array is _very_ slow.  This array is 1.3 GB and takes 200s to write.  That's a write speed of only 6.5MB/s, or a factor of 34x slower.  Any idea why this is?

**Comment by trquinn** [comment]
Is the auxiliary file ASCII or binary?  ASCII would be really slow.

**Comment by ibackus** [comment]
It is ASCII which I can change easily, but reading ASCII should be much faster.  I think the 2 issues are probably ubuffered reading and not preallocating the array.  These little snippets are much faster (10x or more).  The buffered read takes 15s (90 MB/s) and the unbuffered read takes 22s (59 MB/s).

```python
def readtxt(fname, BUF_SIZE=int(1e6)):
    
     with open(fname, 'r') as f:
         # First line in tipsy format is a header
         nlines = int(f.readline().strip())
         # Pre-allocate for speed
         output = np.zeros(nlines)
         # Buffered read
         i0 = 0
         tmp_lines = f.readlines(BUF_SIZE)
         while tmp_lines:
             output[i0:i0 + len(tmp_lines)] = tmp_lines
             tmp_lines = f.readlines(BUF_SIZE)
     return output
 
def readtxt_unbuffered(fname):
    
    with open(fname, 'r') as f:
         nlines = int(f.readline().strip())
         output = np.zeros(nlines)
         for i, line in enumerate(f):
             output[i] = line
         
    return output
```

**Comment by apontzen** [comment]
Looks great - please provide a pull request :-)

**Comment by ibackus** [comment]
happy to...but don't know where tipsy array reading/writing is handled in pynbody.  If you point me to the right place I can put it in there.

**Comment by apontzen** [comment]
It's all in pynbody/snapshot/tipsy.py e.g. line 842 defines the current ASCII reader.

**Comment by ibackus** [comment]
I'm putting this in, but it seems to be impossible for me to reload pynbody when I make a change to a file.  Do you generally have a method for this?  Here's what I get:

```python
reload(pynbody)
Traceback (most recent call last):

  File "<ipython-input-5-26a0e449a9b8>", line 1, in <module>
    reload(pynbody)

  File "/home/ibackus/pypacks/lib/python2.7/site-packages/pynbody/__init__.py", line 34, in <module>
    configuration.configure_snapshot_and_halo_loading_priority()

  File "/home/ibackus/pypacks/lib/python2.7/site-packages/pynbody/configuration.py", line 113, in configure_snapshot_and_halo_loading_priority
    for x in config['snap-class-priority']]

KeyError: <class 'pynbody.snapshot.ramses.RamsesSnap'>
```

**Comment by apontzen** [comment]
Unfortunately this is a wrinkle in developing large python modules generally. I've never found a completely satisfactory way around it for complex codebases.

The simplest workaround it is just to reload what you need during development. E.g. just issue `reload(pynbody.snapshot.tipsy)`. 

Make sure you address the new, reloaded `TipsySnap` class by asking for it explicitly, i.e. `f = pynbody.snapshot.tipsy.TipsySnap(filename)` rather than `f=pynbody.load(filename)` otherwise you may get an old version of the code running (which is very confusing when trying to debug!)

**Comment by ibackus** [comment]
Looking into this more, another reason the ASCII read is so slow is that it seems to get called twice somtimes.  I'm not sure why, but when loading a 10^8 particle array on the cluster I use, it appears the array gets read fully twice by pynbody.

**Comment by apontzen** [comment]
Yes, I think that's probably the correct analysis of why it would end up being called twice. Unfortunately it's hard to see a way around it while keeping the efficiencies associated with lazy-loading only one family at a time for more modern formats. ASCII files just don't scale well for modern simulations!
