### ISSUE TITLE
float type image dimensions in `sph.render_image`

### ISSUE THREAD

**Issue by jakobherpich** [pynbody/pynbody#383]
After migrating my pynbody installation to `python3`, some threads for image rendering fail with the following error message:
```
Exception in thread Thread-719:
Traceback (most recent call last):
  File "/usr/lib64/python3.4/threading.py", line 911, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.4/threading.py", line 859, in run
    self._target(*self._args, **self._kwargs)
  File "/home/herpich/python/pynbody/sph/__init__.py", line 413, in bridge
    X = fn(*args[1:], **kwargs)
  File "/home/herpich/python/pynbody/sph/__init__.py", line 395, in render_fn
    base = fn(*args, **kwargs)
  File "/home/herpich/python/pynbody/sph/__init__.py", line 592, in _render_image
    result = np.zeros((ny, nx), dtype=np.float32)
TypeError: 'float' object cannot be interpreted as an integer
```

This is the traceback (the threads fail and return empty lists):
```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-13-25b26aee6fb7> in <module>()
----> 1 pynbody.plot.stars.render(sim)

/home/herpich/python/pynbody/plot/stars.py in render(sim, filename, r_band, g_band, b_band, r_scale, g_scale, b_scale, dynamic_range, mag_range, width, starsize, plot, axes, ret_im, clear, ret_range)
    143 
    144     r = image(sim.s, qty=r_band + '_lum_den', width=width, log=False,
--> 145               units="pc^-2", clear=False, noplot=True) * r_scale
    146     g = image(sim.s, qty=g_band + '_lum_den', width=width, log=False,
    147               units="pc^-2", clear=False, noplot=True) * g_scale

/home/herpich/python/pynbody/plot/sph.py in image(sim, qty, width, resolution, units, log, vmin, vmax, av_z, filename, z_camera, clear, cmap, title, qtytitle, show_cbar, subplot, noplot, ret_im, fill_nan, fill_val, linthresh, **kwargs)
    410     else:
    411         im = sph.render_image(sim, qty, width / 2, resolution, out_units=units,
--> 412                               kernel=kernel,  z_camera=z_camera, **kwargs)
    413 
    414     if fill_nan:

/home/herpich/python/pynbody/sph/__init__.py in render_image(snap, qty, x2, nx, y2, ny, x1, y1, z_plane, out_units, xy_units, kernel, z_camera, smooth, smooth_in_pixels, force_quiet, approximate_fast, threaded, denoise)
    500                                     out_units, xy_units, kernel, z_camera, smooth,
    501                                     smooth_in_pixels, True,
--> 502                                     num_threads=threaded)
    503     else:
    504         im = base_renderer(snap, qty, x2, nx, y2, ny, x1, y1, z_plane,

/home/herpich/python/pynbody/sph/__init__.py in _threaded_render_image(fn, s, *args, **kwargs)
    378 
    379     # Each output is a 1-element list with a numpy array. Sum them.
--> 380     return sum([o[0] for o in outputs])
    381 
    382 

/home/herpich/python/pynbody/sph/__init__.py in <listcomp>(.0)
    378 
    379     # Each output is a 1-element list with a numpy array. Sum them.
--> 380     return sum([o[0] for o in outputs])
    381 
    382 

IndexError: list index out of range
```

In my case I could fix this by adding the lines
```
nx = int(nx + .5)
ny = int(ny + .5)
```
just before line 592 in `pynbody/sph/__init__.py` but I don't know if that breaks something else, in particular because `nx` and `ny` are being modified before:
```
565     if res_downgrade is not None:
566         # calculate original resolution
567         dx = float(x2 - x1) / nx
568         dy = float(y2 - y1) / ny
569 
570         # degrade resolution
571         nx /= res_downgrade
572         ny /= res_downgrade
```

Since I experienced this issue while calling the `pynbody.plot.stars.render` function, I experienced another issue in the `render` function in `pynbody/plot/stars.py`.
```
In [4]: pynbody.plot.stars.render(sim)
No H2 data found in StarLog file
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-4-25b26aee6fb7> in <module>()
----> 1 pynbody.plot.stars.render(sim)

/home/herpich/python/pynbody/plot/stars.py in render(sim, filename, r_band, g_band, b_band, r_scale, g_scale, b_scale, dynamic_range, mag_range, width, starsize, plot, axes, ret_im, clear, ret_range)
    161 
    162     if mag_range is None:
--> 163         rgbim, mag_max = combine(r, g, b, dynamic_range*2.5)
    164         mag_min = mag_max + 2.5*dynamic_range
    165     else:

/home/herpich/python/pynbody/plot/stars.py in combine(r, g, b, magnitude_range, brightest_mag)
     49         for x in r, g, b:
     50             ordered = np.sort(x.flatten())
---> 51             brightest_mag.append(ordered[-len(ordered) / 5000])
     52 
     53         brightest_mag = max(brightest_mag)

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
```

The issue actually occurs in the `combine` function. Here, I also need to cast a float to an integer. Line 51 should read:
```
 51             brightest_mag.append(ordered[-int(len(ordered) / 5000)])
```

Should I create a pull request with these fixes?

**Comment by apontzen** [comment]
Yes please!
