### ISSUE TITLE
`half_light_radius fails` on `SubSnap`

### ISSUE THREAD

**Issue by jakobherpich** [pynbody/pynbody#388]
When I try to calculate the half light radius of a `SubSnap` of a tipsy simulation output, I get an error because `pynbody` tries to delete an array from a `SubSnap`. The error goes away when I calculate the half light radius of the full snaphot before (See example below). I picked the typsy snapshot from the testdata for this example.

```
In [1]: import pynbody

In [2]: sim = pynbody.load('g15784.lr.01024')

In [3]: h = sim.halos()[1]

In [4]: pynbody.analysis.angmom.faceon(h)
Out[4]: <pynbody.transformation.GenericRotation at 0x7fe3269b66d8>

In [5]: pynbody.analysis.luminosity.half_light_r(h, band='v')
No H2 data found in StarLog file
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-5-58a93b15f27b> in <module>()
----> 1 pynbody.analysis.luminosity.half_light_r(h, band='v')

/home/herpich/python/pynbody/analysis/luminosity.py in half_light_r(sim, band)
    137     testrf = f.LowPass('r', test_r)
    138     min_low_r = 0.0
--> 139     test_l = halo_lum(sim[testrf], band=band)
    140     it = 0
    141     while ((np.abs(test_l - half_l) / half_l) > 0.01):

/home/herpich/python/pynbody/snapshot/__init__.py in __getitem__(self, i)
    270             return self._get_subsnap_from_mask_array(i)
    271         elif isinstance(i, (list, tuple, np.ndarray, filt.Filter)):
--> 272             return IndexedSubSnap(self, i)
    273         elif isinstance(i, int) or isinstance(i, np.int32) or isinstance(i, np.int64):
    274             return IndexedSubSnap(self, (i,))

/home/herpich/python/pynbody/snapshot/__init__.py in __init__(self, base, index_array)
   1813         if isinstance(index_array, filt.Filter):
   1814             self._descriptor = index_array._descriptor
-> 1815             index_array = index_array.where(base)[0]
   1816 
   1817         elif isinstance(index_array, tuple):

/home/herpich/python/pynbody/filt.py in where(self, sim)
     25 
     26     def where(self, sim):
---> 27         return np.where(self(sim))
     28 
     29     def __call__(self, sim):

/home/herpich/python/pynbody/filt.py in __call__(self, sim)
    320         if units.is_unit_like(max_):
    321             max_ = float(
--> 322                 max_.in_units(sim[prop].units, **sim.conversion_context()))
    323 
    324         return (sim[prop] < max_)

/home/herpich/python/pynbody/snapshot/__init__.py in __getitem__(self, i)
    262 
    263         if isinstance(i, str):
--> 264             return self._get_array_with_lazy_actions(i)
    265         elif isinstance(i, slice):
    266             return SubSnap(self, i)

/home/herpich/python/pynbody/snapshot/__init__.py in _get_array_with_lazy_actions(self, name)
    349 
    350         with self._dependency_tracker.calculating(name):
--> 351             self.__resolve_obscuring_family_array(name)
    352 
    353             if not self.lazy_off:

/home/herpich/python/pynbody/snapshot/__init__.py in __resolve_obscuring_family_array(self, name)
    374     def __resolve_obscuring_family_array(self, name):
    375         if name in self.family_keys():
--> 376             self.__remove_family_array_if_derived(name)
    377 
    378         if name in self.family_keys():

/home/herpich/python/pynbody/snapshot/__init__.py in __remove_family_array_if_derived(self, name)
    397     def __remove_family_array_if_derived(self, name):
    398         if self.is_derived_array(name):
--> 399             del self[name]
    400 
    401 

/home/herpich/python/pynbody/snapshot/__init__.py in __delitem__(self, name)
   1724     def __delitem__(self, name):
   1725         # is this the right behaviour?
-> 1726         raise RuntimeError("Arrays can only be deleted from the base snapshot")
   1727 
   1728     def _del_family_array(self, name, family):

RuntimeError: Arrays can only be deleted from the base snapshot

In [6]: pynbody.analysis.luminosity.half_light_r(sim, band='v')
Out[6]: SimArray(6.318972347185018e-05, '4.69e+09 kpc**2 a**2')

In [7]: pynbody.analysis.luminosity.half_light_r(h, band='v')
Out[7]: SimArray(6.0789516675638055e-05, '4.69e+09 kpc**2 a**2')
```

**Comment by apontzen** [comment]
Interesting, what happens if you change line 399 of `snapshot/__init__.py` to `del self.ancestor[name]`?

**Comment by jakobherpich** [comment]
It seems to solve the problem. I hope it doesn't break anything else. I'll create a PR for you to review.

**Comment by apontzen** [comment]
Thanks! Would be awesome if you can also create a unit test for this. Hopefully the other unit tests will catch if this breaks anything.

**Comment by jakobherpich** [comment]
That's a problem for various reasons.

1. I've been unable to run unit tests since I migrated my pynbody installation to python3. Maybe I'm doing it wrong. How do you run unit tests in python3?
2. I've never written a unit test myself.
3. I don't have any time to fix the issues with unit test in python3 because I will be offline for the next 5 weeks.

**Comment by apontzen** [comment]
Ah ok... nosetests should just work on python 3, not sure what would go wrong without knowing more.

**Comment by jakobherpich** [comment]
It just calls python2:

```
herpich@viper:~/src/pynbody/nose> /usr/bin/nosetests
EEEEEEEEEEEEEEEEEEEEE
======================================================================
ERROR: Failure: ImportError (No module named builtins)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/herpich/src/pynbody/nose/ahf_halos_test.py", line 1, in <module>
    import pynbody
  File "/home/herpich/python/pynbody-0.41-py3.4-linux-x86_64.egg/pynbody/__init__.py", line 16, in <module>
    from . import backcompat
  File "/home/herpich/python/pynbody-0.41-py3.4-linux-x86_64.egg/pynbody/backcompat.py", line 2, in <module>
    import builtins
ImportError: No module named builtins
```

and when I run
```
herpich@viper:~/src/pynbody/nose> python3 -m "nose"
```
I get a large number of TypeErrors which I assume are because  there is no integer division in `python3`.

Here is just one of them:
```
Exception in thread Thread-234:
Traceback (most recent call last):
  File "/usr/lib64/python3.4/threading.py", line 911, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.4/threading.py", line 859, in run
    self._target(*self._args, **self._kwargs)
  File "/home/herpich/python/pynbody-0.41-py3.4-linux-x86_64.egg/pynbody/sph/__init__.py", line 413, in bridge
    X = fn(*args[1:], **kwargs)
  File "/home/herpich/python/pynbody-0.41-py3.4-linux-x86_64.egg/pynbody/sph/__init__.py", line 395, in render_fn
    base = fn(*args, **kwargs)
  File "/home/herpich/python/pynbody-0.41-py3.4-linux-x86_64.egg/pynbody/sph/__init__.py", line 789, in _to_3d_grid
    result = np.zeros((nx, ny, nz), dtype=np.float32)
TypeError: 'float' object cannot be interpreted as an integer
```

**Comment by jakobherpich** [comment]
The binary `nosetests-3.4` uses python2.7 as well. I'm afraid there is something messed up in my installation.
