### ISSUE TITLE
Issue accessing profiles with ChaNGa

### ISSUE THREAD

**Issue by anchwr** [pynbody/pynbody#404]
I am encountering an issue with accessing the pot, v_circ, j_circ, E_circ, Q, omega, and kappa profiles in snapshots generated with ChaNGa. It looks like the error has to do with how the ChaNGa output files store the gravitational softening length. I've reproduced the error below:
>>> import pynbody
>>> s = pynbody.load('cosmo25p.768sg1bwK1BHe75.008192')
>>> h = s.halos(dosort=True)
>>> h2 = h.load_copy(288)
>>> h2.physical_units()
>>> pynbody.analysis.angmom.faceon(h2)
<pynbody.transformation.GenericRotation object at 0x7fd9e0002c90>
>>> p = pynbody.analysis.profile.Profile(h2,min=0.02,max=10,nbins=100)
>>> p['v_circ']
pynbody.analysis.profile : Profile v_circ -- this routine assumes the disk is in the x-y plane
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda/lib/python2.7/site-packages/pynbody/analysis/profile.py", line 434, in __getitem__
    return self._get_profile(name)
  File "/opt/anaconda/lib/python2.7/site-packages/pynbody/analysis/profile.py", line 346, in _get_profile
    self._profiles[name] = Profile._profile_registry[x[0]](self, *args)
  File "/opt/anaconda/lib/python2.7/site-packages/pynbody/analysis/profile.py", line 724, in v_circ
    grav_sim, p['rbins']).in_units(p.sim['vel'].units)
  File "/opt/anaconda/lib/python2.7/site-packages/pynbody/gravity/calc.py", line 90, in midplane_rot_curve
    eps += f.properties['eps']
  File "/opt/anaconda/lib/python2.7/site-packages/pynbody/simdict.py", line 61, in __getitem__
    raise KeyError, k
KeyError: 'eps'

As far as I know, this parameter only appears in the tipsy binary files with ChaNGa. Is there any way that it could be made into a keyword argument? (Perhaps it already is and I simply haven't hit on the right combination of words and format?) Thanks!

**Comment by apontzen** [comment]
I think the workaround would be to set `s.properties['eps']` manually to the value you want for the softening. Could you try this and see if it helps?

**Comment by anchwr** [comment]
That works! Thank you very much!
