### ISSUE TITLE
Issue generating image for Gadget snapshot

### ISSUE THREAD

**Issue by dumasj** [pynbody/pynbody#448]
When I try to generate an image for the following section of my code, I get the error below. This is a snapshot from a non-cosmological run with P-Gadget3.
        
```
        f.physical_units()

        f_gal2 = f[(f['iord']>0)&(f['iord']<15000000)]

        pos = f_gal2.star['pos']

        plt.clf()

        pynbody.plot.sph.image(f_gal2.star, qty='rho', width='300 kpc', cmap='GnBu', vmin=pow(10, 0), vmax=pow(10, 9), show_cbar=False)#, resolution=1000)
```

```
Exception in thread Thread-24:
Traceback (most recent call last):
  File "/opt/apps/intel17/python/2.7.13/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/opt/apps/intel17/python/2.7.13/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home1/04966/dumasj/.local/lib/python2.7/site-packages/pynbody/sph/__init__.py", line 425, in bridge
    X = fn(*args[1:], **kwargs)
  File "/home1/04966/dumasj/.local/lib/python2.7/site-packages/pynbody/sph/__init__.py", line 407, in render_fn
    base = fn(*args, **kwargs)
  File "/home1/04966/dumasj/.local/lib/python2.7/site-packages/pynbody/sph/__init__.py", line 557, in _render_image
    snap_proxy[arname] = snap[arname]
  File "/home1/04966/dumasj/.local/lib/python2.7/site-packages/pynbody/snapshot/__init__.py", line 263, in __getitem__
    return self._get_array_with_lazy_actions(i)
  File "/home1/04966/dumasj/.local/lib/python2.7/site-packages/pynbody/snapshot/__init__.py", line 356, in _get_array_with_lazy_actions
    self.__derive_if_required(name)
  File "/home1/04966/dumasj/.local/lib/python2.7/site-packages/pynbody/snapshot/__init__.py", line 371, in __derive_if_required
    self._derive_array(name)
  File "/home1/04966/dumasj/.local/lib/python2.7/site-packages/pynbody/snapshot/__init__.py", line 1941, in _derive_array
    self.base._derive_array(array_name, self._unifamily)
  File "/home1/04966/dumasj/.local/lib/python2.7/site-packages/pynbody/snapshot/__init__.py", line 1470, in _derive_array
    result = fn(self[fam])
  File "/home1/04966/dumasj/.local/lib/python2.7/site-packages/pynbody/sph/__init__.py", line 137, in smooth
    self.kdtree.populate('hsm', config['sph']['smooth-particles'])
  File "/home1/04966/dumasj/.local/lib/python2.7/site-packages/pynbody/sph/kdtree.py", line 114, in populate
    smx = kdmain.nn_start(self.kdtree, int(nn), self.boxsize)
ValueError: The particles span a region larger than the specified boxsize


Traceback (most recent call last):
  File "saveimg_star3.py", line 107, in <module>
    save_all_img(50, 50)
  File "saveimg_star3.py", line 95, in save_all_img
    saveimg(s, i)
  File "saveimg_star3.py", line 36, in saveimg
    pynbody.plot.sph.image(f.star, qty='rho', width='6800 kpc')#, cmap='GnBu', vmin=pow(10, 0), vmax=pow(10, 9), show_cbar=False)#, resolution=1000)
  File "/home1/04966/dumasj/.local/lib/python2.7/site-packages/pynbody/plot/sph.py", line 423, in image
    kernel=kernel,  z_camera=z_camera, **kwargs)
  File "/home1/04966/dumasj/.local/lib/python2.7/site-packages/pynbody/sph/__init__.py", line 518, in render_image
    num_threads=threaded)
  File "/home1/04966/dumasj/.local/lib/python2.7/site-packages/pynbody/sph/__init__.py", line 392, in _threaded_render_image
    return sum([o[0] for o in outputs])
IndexError: list index out of range
```

Thanks,

Julie

**Comment by apontzen** [comment]
Thanks! One extra piece of information that would be useful: if you `print f.properties['boxsize']` what value is reported?

**Comment by dumasj** [comment]
The value for boxsize is 0.00e+00 kpc.

**Comment by apontzen** [comment]
Thanks. So I think this should now be fixed if you install this branch: https://github.com/pynbody/pynbody/pull/449 e.g. via `pip install git+https://github.com/pynbody/pynbody.git@isolated-kdtree`. Please give it a go and let me know whether things start working.

**Comment by dumasj** [comment]
Thanks. The issue is resolved, the images are generated now. 

My delay is because I see another issue with reading the time value in the snapshot header. I can confirm that pynbody version 0.41 outputs the correct time, but this branch doesn't using the lines below.

 f.physical_units()

 t = f.properties['time'].in_units('Gyr')

print t

**Comment by apontzen** [comment]
Thanks @dumasj. Looking at it, I think the problem must be arising from this commit: 8f8207a

On that basis, I'd be interested to know what you get for `f.header.HubbleParam`? I guess it must be non-zero even in your isolated run?

**Comment by dumasj** [comment]
The value for `f.header.HubbleParam` is 0.7.

**Comment by apontzen** [comment]
Thanks. Actually could you report the entire contents of f.header as surely there must be a give-away somewhere in there that we can use to tell it’s not a cosmological run...

**Comment by dumasj** [comment]
The values for `f.properties` are {'a': 1.0, 'omegaL0': 0.0, 'omegaM0': 0.0, 'h': 0.7, 'boxsize': Unit("0.00e+00 kpc"), 'time': Unit("4.57e-02 kpc s km**-1")}.

**Comment by apontzen** [comment]
Thanks! I tried pushing a further fix to the same branch - could you try and see if it now fully works?

**Comment by dumasj** [comment]
I get the following error when I tried with the same branch.

```
Traceback (most recent call last):
  File "saveimg_star3.py", line 117, in <module>
    save_all_img(1, 1)
  File "saveimg_star3.py", line 91, in save_all_img
    s = pynbody.load("int1e1i0_cc11_v150_g01_z0p1.gadget_snapshot_00%d"%i) #specify filename and the extension
  File "/home1/04966/dumasj/.local/lib/python2.7/site-packages/pynbody/snapshot/__init__.py", line 1952, in load
    return c(filename, *args, **kwargs)
  File "/home1/04966/dumasj/.local/lib/python2.7/site-packages/pynbody/snapshot/gadget.py", line 798, in __init__
    self._decorate()    
  File "/home1/04966/dumasj/.local/lib/python2.7/site-packages/pynbody/snapshot/__init__.py", line 1575, in _decorate
    fn(self)
  File "/home1/04966/dumasj/.local/lib/python2.7/site-packages/pynbody/snapshot/gadget.py", line 1182, in do_units
    if not _header_suggests_cosmological(sim):
  File "/home1/04966/dumasj/.local/lib/python2.7/site-packages/pynbody/snapshot/gadget.py", line 1168, in _header_suggests_cosmological
    return (gadget_header.HubbleParam != 0.) and (gadget_header.Omega0 != 0.) and (gadget_header.BoxSize != 0.)
  File "/home1/04966/dumasj/.local/lib/python2.7/site-packages/pynbody/snapshot/__init__.py", line 444, in __getattr__
    type(self).__name__, name))
AttributeError: 'GadgetSnap' object has no attribute 'HubbleParam'
```

**Comment by apontzen** [comment]
Argh, sorry! That is just me making a stupid mistake. Please try again – third time lucky!

**Comment by dumasj** [comment]
Thanks. I confirm that it is working correctly now, both issues are fixed.

**Comment by apontzen** [comment]
Excellent, merged fix into master.
