### ISSUE TITLE
Pynbody breaking with Python 3.7

### ISSUE THREAD

**Issue by Martin-Rey** [pynbody/pynbody#498]
Hi,

I found myself playing around with Python 3.7 following a fresh Anaconda install. The unit test on 3.7 fails for me, specifically the gadgethdf_test.py with the following error:

```
nosetests gadgethdf_test.py 
...EE....
======================================================================
ERROR: Check that halo loading works
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ucapmre/anaconda3/lib/python3.7/site-packages/pynbody-0.46-py3.7-linux-x86_64.egg/pynbody/halo/__init__.py", line 128, in _halo_generator
    if i == i_stop: raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ucapmre/anaconda3/lib/python3.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/ucapmre/pynbody/nose/gadgethdf_test.py", line 71, in test_halo_loading
    for i,halo in enumerate(h[0:10]) :
  File "/home/ucapmre/anaconda3/lib/python3.7/site-packages/pynbody-0.46-py3.7-linux-x86_64.egg/pynbody/halo/__init__.py", line 96, in __getitem__
    for x in self._halo_generator(item.start,item.stop) : pass
RuntimeError: generator raised StopIteration

======================================================================
ERROR: Check that halo values (and sizes) agree with pyread_gadget_hdf5
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ucapmre/anaconda3/lib/python3.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/ucapmre/pynbody/nose/gadgethdf_test.py", line 109, in test_halo_values
    for i,halo in enumerate(h[0:10]) :
  File "/home/ucapmre/anaconda3/lib/python3.7/site-packages/pynbody-0.46-py3.7-linux-x86_64.egg/pynbody/halo/__init__.py", line 96, in __getitem__
    for x in self._halo_generator(item.start,item.stop) : pass
RuntimeError: generator raised StopIteration
-------------------- >> begin captured stdout << ---------------------
User gave testdata/Test_NOSN_NOZCOOL_L010N0128/data/subhalos_103/subhalo_103.0.hdf5
This is a SubFind output filetype
Considering 8 subfiles
Note h=0.702 in this simulation and snapshot is at a=0.167 (z=5.000)
Number of Elements Tracked 9, they are
b'Hydrogen'
b'Helium'
b'Carbon'
b'Nitrogen'
b'Oxygen'
b'Neon'
b'Magnesium'
b'Silicon'
b'Iron'
Now select the requested variable FOF/Mass/
Reading from testdata/Test_NOSN_NOZCOOL_L010N0128/data/subhalos_103/subhalo_103.0.hdf5
Reading from testdata/Test_NOSN_NOZCOOL_L010N0128/data/subhalos_103/subhalo_103.1.hdf5
Reading from testdata/Test_NOSN_NOZCOOL_L010N0128/data/subhalos_103/subhalo_103.2.hdf5
Reading from testdata/Test_NOSN_NOZCOOL_L010N0128/data/subhalos_103/subhalo_103.3.hdf5
Reading from testdata/Test_NOSN_NOZCOOL_L010N0128/data/subhalos_103/subhalo_103.4.hdf5
Reading from testdata/Test_NOSN_NOZCOOL_L010N0128/data/subhalos_103/subhalo_103.5.hdf5
Reading from testdata/Test_NOSN_NOZCOOL_L010N0128/data/subhalos_103/subhalo_103.6.hdf5
Reading from testdata/Test_NOSN_NOZCOOL_L010N0128/data/subhalos_103/subhalo_103.7.hdf5
No conversion - still in Code units
Done 

--------------------- >> end captured stdout << ----------------------

----------------------------------------------------------------------
Ran 9 tests in 3.842s

FAILED (errors=2)
```

I think I have identified the reason in a change of behavior of StopIteration (https://www.python.org/dev/peps/pep-0479/) which is now fully operational in 3.7. This change makes StopIteration turn into a RuntimeError once raised inside a generator and is not backward compatible. Pynbody has at least one line relying on such a mechanic:
https://github.com/pynbody/pynbody/blob/ddbf3d272a818f4df4ec8180c0e55323fefdcf27/pynbody/halo/__init__.py#L128

Best
Martin

**Comment by apontzen** [comment]
Should now be fixed - reopen if you have any problems!
