### ISSUE TITLE
Circular Dependency in Temperature Calculation

### ISSUE THREAD

**Issue by rennehan** [pynbody/pynbody#532]
> That code is only called if an array is missing so the assumption is that only one of temp and u is missing. If this were not true you’d get a circular dependency exception so this is not related to the zeros you are seeing.

_Originally posted by @apontzen in https://github.com/pynbody/pynbody/issues/452#issuecomment-389807436_

I would like to bring this up again because there is indeed a circular dependency in the snapshots that I am loading. I am loading GadgetHDF5 files using pynbody (really GIZMO files, but that doesn't matter) and when I try to load the **temp** field it gives a DependencyError which is shown in the copy-paste at the bottom of this report.

The reason is that in the calculation of **mu** for the temperature the code tries to load the HI fraction which does not exist in my simulations, and then it tries to calculate **mu** based on the temperature! A circular dependency. I think the easiest solution is, in the code below (**derived.py**), to make an exception for the DependencyError in addition to the KeyError.

```python
@SimSnap.derived_quantity
def mu(sim, t0=None):
        """mean molecular mass, i.e. the mean atomic mass per particle"""
        try:
                x = sim["HI"] + 2 * sim["HII"] + sim["HeI"] + \
            2 * sim["HeII"] + 3 * sim["HeIII"]
                x = x**-1
        except KeyError:
                x = np.empty(len(sim)).view(array.SimArray)
                if t0 is None:
                        t0 = sim['temp']
                x[np.where(t0 >= 1e4)[0]] = 0.59
                x[np.where(t0 < 1e4)[0]] = 1.3

        x.units = units.Unit("1")
        return x
```

```
DependencyError                           Traceback (most recent call last)
<ipython-input-9-4bad0ae96528> in <module>
----> 1 h[1].g['temp']

/usr/lib/python3.7/site-packages/pynbody/snapshot/__init__.py in __getitem__(self, i)
    262 
    263         if isinstance(i, str):
--> 264             return self._get_array_with_lazy_actions(i)
    265         elif isinstance(i, slice):
    266             return SubSnap(self, i)

/usr/lib/python3.7/site-packages/pynbody/snapshot/__init__.py in _get_array_with_lazy_actions(self, name)
    355                     self.__load_if_required(name)
    356                 if not self.lazy_derive_off:
--> 357                     self.__derive_if_required(name)
    358 
    359             return self._get_array(name)

/usr/lib/python3.7/site-packages/pynbody/snapshot/__init__.py in __derive_if_required(self, name)
    370     def __derive_if_required(self, name):
    371         if name not in list(self.keys()):
--> 372             self._derive_array(name)
    373 
    374     def __resolve_obscuring_family_array(self, name):

/usr/lib/python3.7/site-packages/pynbody/snapshot/__init__.py in _derive_array(self, array_name, fam)
   1971     def _derive_array(self, array_name, fam=None):
   1972         if fam is self._unifamily or fam is None:
-> 1973             self.base._derive_array(array_name, self._unifamily)
   1974 
   1975 

/usr/lib/python3.7/site-packages/pynbody/snapshot/__init__.py in _derive_array(self, array_name, fam)
   1803 
   1804     def _derive_array(self, array_name, fam=None):
-> 1805         self.base._derive_array(array_name, fam)
   1806 
   1807     def family_keys(self, fam=None):

/usr/lib/python3.7/site-packages/pynbody/snapshot/__init__.py in _derive_array(self, name, fam)
   1500                         name, always_writable=True)
   1501                 else:
-> 1502                     result = fn(self[fam])
   1503                     ndim = result.shape[-1] if len(
   1504                         result.shape) > 1 else 1

/usr/lib/python3.7/site-packages/pynbody/derived.py in temp(self)
    268         temp = (self['u'] * units.m_p / units.k) * (mu_est * (gamma - 1))
    269         temp.convert_units("K")
--> 270         mu_est = mu(self, temp)
    271     return temp
    272 

/usr/lib/python3.7/site-packages/pynbody/derived.py in mu(sim, t0)
    232         try:
    233                 x = sim["HI"] + 2 * sim["HII"] + sim["HeI"] + \
--> 234             2 * sim["HeII"] + 3 * sim["HeIII"]
    235                 x = x**-1
    236         except KeyError:

/usr/lib/python3.7/site-packages/pynbody/snapshot/__init__.py in __getitem__(self, i)
    262 
    263         if isinstance(i, str):
--> 264             return self._get_array_with_lazy_actions(i)
    265         elif isinstance(i, slice):
    266             return SubSnap(self, i)

/usr/lib/python3.7/site-packages/pynbody/snapshot/__init__.py in _get_array_with_lazy_actions(self, name)
    355                     self.__load_if_required(name)
    356                 if not self.lazy_derive_off:
--> 357                     self.__derive_if_required(name)
    358 
    359             return self._get_array(name)

/usr/lib/python3.7/site-packages/pynbody/snapshot/__init__.py in __derive_if_required(self, name)
    370     def __derive_if_required(self, name):
    371         if name not in list(self.keys()):
--> 372             self._derive_array(name)
    373 
    374     def __resolve_obscuring_family_array(self, name):

/usr/lib/python3.7/site-packages/pynbody/snapshot/__init__.py in _derive_array(self, array_name, fam)
   1971     def _derive_array(self, array_name, fam=None):
   1972         if fam is self._unifamily or fam is None:
-> 1973             self.base._derive_array(array_name, self._unifamily)
   1974 
   1975 

/usr/lib/python3.7/site-packages/pynbody/snapshot/__init__.py in _derive_array(self, name, fam)
   1500                         name, always_writable=True)
   1501                 else:
-> 1502                     result = fn(self[fam])
   1503                     ndim = result.shape[-1] if len(
   1504                         result.shape) > 1 else 1

/usr/lib/python3.7/site-packages/pynbody/snapshot/gadgethdf.py in HI(sim)
    808     import pynbody.analysis.hifrac
    809 
--> 810     return pynbody.analysis.hifrac.calculate(sim.g,ion='hi')
    811 
    812 ## Need to use the ionisation fraction calculation here which gives ionisation fraction

/usr/lib/python3.7/site-packages/pynbody/analysis/hifrac.py in calculate(sim, ion, selfshield)
     51     z = np.zeros(len(sim.gas)).view(np.ndarray)
     52     z[:] = sim.properties['z']
---> 53     y = np.log10(sim.gas['temp']).view(np.ndarray)
     54     x = np.log10(sim.gas['rho'].in_units('m_p cm^-3')).view(np.ndarray)
     55     n = len(sim.gas)

/usr/lib/python3.7/site-packages/pynbody/snapshot/__init__.py in __getitem__(self, i)
    262 
    263         if isinstance(i, str):
--> 264             return self._get_array_with_lazy_actions(i)
    265         elif isinstance(i, slice):
    266             return SubSnap(self, i)

/usr/lib/python3.7/site-packages/pynbody/snapshot/__init__.py in _get_array_with_lazy_actions(self, name)
    348             return self._get_array(name)
    349 
--> 350         with self._dependency_tracker.calculating(name):
    351             self.__resolve_obscuring_family_array(name)
    352 

/usr/lib/python3.7/site-packages/pynbody/dependencytracker.py in __enter__(self)
     13         self.tracker._calculation_lock.__enter__()
     14         if self.name in self.tracker._current_calculation_stack:
---> 15             raise DependencyError("Circular dependency")
     16         self.tracker._push(self.name)
     17 

DependencyError: Circular dependency
```

**Comment by apontzen** [comment]
Thanks for bringing this up. I agree the `DependencyError` is surprising, but technically it is the correctly defined behaviour. When getting an array, pynbody first tries to fetch it from disk. If that fails, it tries to derive it. Derived definitions are given for a lot of different functions, including "temperature from internal energy", "internal energy from temperature", "ionisation fraction from temperature" etc; this catches a lot of useful cases where different formats choose to store some variety of different thermodynamic quantities but not all those you want. But when the stored information does not meet some minimum standards, all these functions end up pointing at each other.

The solution would be to come up with a more helpful error message generally, I think, rather than to change behaviour for this specific case. This could prompt users to create the missing array if they know how to. 

In your own code you could create a new derived `mu` function that has your approximate implementation.

Let me know if you have any further thoughts.

**Comment by Astrokiwi** [comment]
I've found a related error. The DependencyError when trying to plot 'temp' when 'temp' isn't defined doesn't kill all the threads correctly, so it's necessary to hit ctrl-C to get back to the interactive terminal. If I then go and try to plot something that _is_ defined - e.g. 'u' - then it just hangs. The traceback makes it look like it's a thread deadlock. So there's something wrong with the multithreading here. Full example below:

`In [4]: pynbody.plot.sph.image(snap.g,qty="u",width=.1)                                                                                                                             
Out[4]: 
SimArray([[0.01058661, 0.01083771, 0.01108881, ..., 0.00504672,
           0.00504253, 0.00503835],
          [0.01084276, 0.01109859, 0.01135442, ..., 0.00521066,
           0.00520174, 0.00519281],
          [0.01109891, 0.01135947, 0.01162003, ..., 0.00537461,
           0.00536094, 0.00534726],
          ...,
          [0.00981404, 0.01022757, 0.0106411 , ..., 0.00386054,
           0.00376232, 0.00366411],
          [0.00963205, 0.01004598, 0.0104599 , ..., 0.00366878,
           0.00357422, 0.00347966],
          [0.00945006, 0.00986438, 0.0102787 , ..., 0.00347702,
           0.00338611, 0.00329521]], dtype=float32, 'km**2 a s**-2')

In [5]: pynbody.plot.sph.image(snap.g,qty="temp",width=.1)                                                                                                                          
Exception in thread Thread-3176:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pynbody/sph/__init__.py", line 440, in bridge
    X = fn(*args[1:], **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pynbody/sph/__init__.py", line 422, in render_fn
    base = fn(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pynbody/sph/__init__.py", line 572, in _render_image
    snap_proxy[arname] = snap[arname]
  File "/usr/local/lib/python3.6/dist-packages/pynbody/snapshot/__init__.py", line 264, in __getitem__
    return self._get_array_with_lazy_actions(i)
  File "/usr/local/lib/python3.6/dist-packages/pynbody/snapshot/__init__.py", line 357, in _get_array_with_lazy_actions
    self.__derive_if_required(name)
  File "/usr/local/lib/python3.6/dist-packages/pynbody/snapshot/__init__.py", line 372, in __derive_if_required
    self._derive_array(name)
  File "/usr/local/lib/python3.6/dist-packages/pynbody/snapshot/__init__.py", line 1973, in _derive_array
    self.base._derive_array(array_name, self._unifamily)
  File "/usr/local/lib/python3.6/dist-packages/pynbody/snapshot/__init__.py", line 1502, in _derive_array
    result = fn(self[fam])
  File "/usr/local/lib/python3.6/dist-packages/pynbody/derived.py", line 270, in temp
    mu_est = mu(self, temp)
  File "/usr/local/lib/python3.6/dist-packages/pynbody/derived.py", line 234, in mu
    2 * sim["HeII"] + 3 * sim["HeIII"]
  File "/usr/local/lib/python3.6/dist-packages/pynbody/snapshot/__init__.py", line 264, in __getitem__
    return self._get_array_with_lazy_actions(i)
  File "/usr/local/lib/python3.6/dist-packages/pynbody/snapshot/__init__.py", line 357, in _get_array_with_lazy_actions
    self.__derive_if_required(name)
  File "/usr/local/lib/python3.6/dist-packages/pynbody/snapshot/__init__.py", line 372, in __derive_if_required
    self._derive_array(name)
  File "/usr/local/lib/python3.6/dist-packages/pynbody/snapshot/__init__.py", line 1973, in _derive_array
    self.base._derive_array(array_name, self._unifamily)
  File "/usr/local/lib/python3.6/dist-packages/pynbody/snapshot/__init__.py", line 1502, in _derive_array
    result = fn(self[fam])
  File "/usr/local/lib/python3.6/dist-packages/pynbody/snapshot/gadgethdf.py", line 810, in HI
    return pynbody.analysis.hifrac.calculate(sim.g,ion='hi')
  File "/usr/local/lib/python3.6/dist-packages/pynbody/analysis/hifrac.py", line 53, in calculate
    y = np.log10(sim.gas['temp']).view(np.ndarray)
  File "/usr/local/lib/python3.6/dist-packages/pynbody/snapshot/__init__.py", line 264, in __getitem__
    return self._get_array_with_lazy_actions(i)
  File "/usr/local/lib/python3.6/dist-packages/pynbody/snapshot/__init__.py", line 350, in _get_array_with_lazy_actions
    with self._dependency_tracker.calculating(name):
  File "/usr/local/lib/python3.6/dist-packages/pynbody/dependencytracker.py", line 15, in __enter__
    raise DependencyError("Circular dependency")
pynbody.dependencytracker.DependencyError: Circular dependency

^C---------------------------------------------------------------------------
KeyboardInterrupt                         Traceback (most recent call last)
<ipython-input-5-7ef973ef03aa> in <module>
----> 1 pynbody.plot.sph.image(snap.g,qty="temp",width=.1)

/usr/local/lib/python3.6/dist-packages/pynbody/plot/sph.py in image(sim, qty, width, resolution, units, log, vmin, vmax, av_z, filename, z_camera, clear, cmap, title, qtytitle, show_cbar, subplot, noplot, ret_im, fill_nan, fill_val, linthresh, **kwargs)
    421     else:
    422         im = sph.render_image(sim, qty, width / 2, resolution, out_units=units,
--> 423                               kernel=kernel,  z_camera=z_camera, **kwargs)
    424 
    425     if fill_nan:

/usr/local/lib/python3.6/dist-packages/pynbody/sph/__init__.py in render_image(snap, qty, x2, nx, y2, ny, x1, y1, z_plane, out_units, xy_units, kernel, z_camera, smooth, smooth_in_pixels, force_quiet, approximate_fast, threaded, denoise)
    531                                     out_units, xy_units, kernel, z_camera, smooth,
    532                                     smooth_in_pixels, True,
--> 533                                     num_threads=threaded)
    534     else:
    535         im = base_renderer(snap, qty, x2, nx, y2, ny, x1, y1, z_plane,

/usr/local/lib/python3.6/dist-packages/pynbody/sph/__init__.py in _threaded_render_image(fn, s, *args, **kwargs)
    400 
    401         for t in ts:
--> 402             t.join()
    403 
    404     # Each output is a 1-element list with a numpy array. Sum them.

/usr/lib/python3.6/threading.py in join(self, timeout)
   1054 
   1055         if timeout is None:
-> 1056             self._wait_for_tstate_lock()
   1057         else:
   1058             # the behavior of a negative timeout isn't documented, but

/usr/lib/python3.6/threading.py in _wait_for_tstate_lock(self, block, timeout)
   1070         if lock is None:  # already determined that the C code is done
   1071             assert self._is_stopped
-> 1072         elif lock.acquire(block, timeout):
   1073             lock.release()
   1074             self._stop()

KeyboardInterrupt: 

In [6]: pynbody.plot.sph.image(snap.g,qty="u",width=.1)                                                                                                                             
^C---------------------------------------------------------------------------
KeyboardInterrupt                         Traceback (most recent call last)
<ipython-input-6-856b382febc3> in <module>
----> 1 pynbody.plot.sph.image(snap.g,qty="u",width=.1)

/usr/local/lib/python3.6/dist-packages/pynbody/plot/sph.py in image(sim, qty, width, resolution, units, log, vmin, vmax, av_z, filename, z_camera, clear, cmap, title, qtytitle, show_cbar, subplot, noplot, ret_im, fill_nan, fill_val, linthresh, **kwargs)
    421     else:
    422         im = sph.render_image(sim, qty, width / 2, resolution, out_units=units,
--> 423                               kernel=kernel,  z_camera=z_camera, **kwargs)
    424 
    425     if fill_nan:

/usr/local/lib/python3.6/dist-packages/pynbody/sph/__init__.py in render_image(snap, qty, x2, nx, y2, ny, x1, y1, z_plane, out_units, xy_units, kernel, z_camera, smooth, smooth_in_pixels, force_quiet, approximate_fast, threaded, denoise)
    531                                     out_units, xy_units, kernel, z_camera, smooth,
    532                                     smooth_in_pixels, True,
--> 533                                     num_threads=threaded)
    534     else:
    535         im = base_renderer(snap, qty, x2, nx, y2, ny, x1, y1, z_plane,

/usr/local/lib/python3.6/dist-packages/pynbody/sph/__init__.py in _threaded_render_image(fn, s, *args, **kwargs)
    400 
    401         for t in ts:
--> 402             t.join()
    403 
    404     # Each output is a 1-element list with a numpy array. Sum them.

/usr/lib/python3.6/threading.py in join(self, timeout)
   1054 
   1055         if timeout is None:
-> 1056             self._wait_for_tstate_lock()
   1057         else:
   1058             # the behavior of a negative timeout isn't documented, but

/usr/lib/python3.6/threading.py in _wait_for_tstate_lock(self, block, timeout)
   1070         if lock is None:  # already determined that the C code is done
   1071             assert self._is_stopped
-> 1072         elif lock.acquire(block, timeout):
   1073             lock.release()
   1074             self._stop()

KeyboardInterrupt: 
`

**Comment by apontzen** [comment]
Thanks @astrokiwi. This turned out to be an issue related to the order in which locks are acquired/released. Could you check #545 fixes it for you?

**Comment by Astrokiwi** [comment]
Thanks Andrew, that fixed it - for my test case at least.  The threads don't hang anymore, and will properly exit with `RuntimeError: There was a problem with the multi-threaded image render. Try running again with threaded=False to debug the underlying error.`. If I hit ctrl-C after the `DependencyError` shows up, it still unlocks the threads correctly.
