### ISSUE TITLE
Trying to Fix OpenMP issue

### ISSUE THREAD

**Issue by steventgk** [pynbody/pynbody#617]
I have been trying to fix the openmp limitation on my mac following the guidance on https://pynbody.github.io/pynbody/tutorials/threads.html

In doing so I linked CC to the gcc-10 install in the path. Now reinstalling pynbody using pip has led to the following error on import:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/pynbody/__init__.py", line 33, in <module>
    from . import util, filt, array, family, snapshot
  File "/usr/local/lib/python3.8/site-packages/pynbody/util.py", line 30, in <module>
    from ._util import *
ImportError: dlopen(/usr/local/lib/python3.8/site-packages/pynbody/_util.cpython-38-darwin.so, 2): Symbol not found: _omp_get_num_threads
  Referenced from: /usr/local/lib/python3.8/site-packages/pynbody/_util.cpython-38-darwin.so
  Expected in: flat namespace
 in /usr/local/lib/python3.8/site-packages/pynbody/_util.cpython-38-darwin.so

 - OS: macOS Big Sur - version 11.4 (20F71)
 - Python version: 3.8.10
 - Numpy version: 1.12.0
 - Pynbody version: 1.0.2

Any help is greatly appreciated.

Thanks,

Steven

**Comment by steventgk** [comment]
So an update on progress with this. I did a clean install of my OS and had some teething problems but managed to get things to settle down. I followed the steps of installing the latest gcc, linking and manually rebuilding. In the process, I had to disable security which blocks external apps from running:

sudo spctl --master-disable

This allowed for a successful build and installation. Pynbody now also recognises all my cores for openmp.
